import 'package:flutter/material.dart';
import 'package:flutter_mattermost/features/admin/domain/entities/resource_keys.dart';

/// أقسام Admin Console.
enum AdminConsoleSection {
  editionAndLicense,

  workSpaceOptimization,
  systemStatistics,
  teamStatistics,
  serverLogs,
  analytics,
  usersManagement,
  generalSettings,
  webServer,
  database,
  fileStorage,
  smtp,
  authentication,
  signup,
  email,
  password,
  mfa,
  adALDAP,
  saml,
  openIDConnect,
  guestAccess,
  notifications,
  security,
  compliance,
  cors,
  rolesSchemes,
  groups,
  license,
  pluginsManagement,
  dataRetention,
  contentFlagging,
  accessControl,
  sharedChannels,
  teamsManagement,
  channelsManagement,
  delegatedGranularAdministration,
  users,
  teams,
  channels,
  permissions,
  userAttributes,
  elasticsearch,
  imageProxy,
  pushNotificationsServer,
  highAvailability,
  cacheSettings,
  rateLimiting,
  logging,
  sessionLengths,
  performanceMonitoring,
  developer,
  customization,
  localization,
  usersAndTeams,
  classificationMarkings,
  systemWideNotifications,
  emoji,
  posts,
  recap,
  dataSpillageHandling,
  fileSharingAndDownloads,
  publicLinks,
  notices,
  agents,
  calls,
  playbooks,
  integrationManagement,
  botAccounts,
  gif,
  embedding,
  complianceExport,
  complicanceMonitoring,
  auditLogging,
  customTermsOfService,
  features,
  featureFlags;

  /// مجموعة الأقسام والـ Categories كما تظهر في القائمة الجانبية في Mattermost.
  static const List<(String, IconData, List<AdminConsoleSection>)>
  sectionsGroup = [
    ('ABOUT', Icons.info_outline, [AdminConsoleSection.editionAndLicense]),
    (
      ResourceKeys.reporting,
      Icons.people_alt_outlined,
      [
        AdminConsoleSection.workSpaceOptimization,
        AdminConsoleSection.systemStatistics,
        AdminConsoleSection.teamStatistics,
        AdminConsoleSection.serverLogs,
      ],
    ),
    // (
    //   ResourceKeys.userManagement,
    //   Icons.bar_chart_rounded,
    //   [
    //     AdminConsoleSection.users,
    //     AdminConsoleSection.groups,
    //     AdminConsoleSection.teams,
    //     AdminConsoleSection.channels,
    //     AdminConsoleSection.permissions,
    //     AdminConsoleSection.delegatedGranularAdministration,
    //   ],
    // ),
    // (
    //   ResourceKeys.reporting,
    //   Icons.bar_chart_rounded,
    //   [
    //     AdminConsoleSection.overview,
    //     AdminConsoleSection.analytics,
    //     AdminConsoleSection.logs,
    //   ],
    // ),
    (
      'AUTHENTICATION',
      Icons.lock_person_outlined,
      [
        AdminConsoleSection.signup,
        AdminConsoleSection.email,
        AdminConsoleSection.password,
        AdminConsoleSection.mfa,
        AdminConsoleSection.adALDAP,
        AdminConsoleSection.saml,
        AdminConsoleSection.openIDConnect,
        AdminConsoleSection.guestAccess,
      ],
    ),
    (
      'SITE CONFIGURATION',
      Icons.settings_applications_outlined,
      [
        AdminConsoleSection.generalSettings,
        AdminConsoleSection.authentication,
        AdminConsoleSection.notifications,
        AdminConsoleSection.security,
      ],
    ),
    (
      'ENVIRONMENT',
      Icons.dns_outlined,
      [
        AdminConsoleSection.webServer,
        AdminConsoleSection.database,
        AdminConsoleSection.fileStorage,
        AdminConsoleSection.smtp,
      ],
    ),
    (
      'COMPLIANCE & SECURITY',
      Icons.shield_outlined,
      [
        AdminConsoleSection.compliance,
        AdminConsoleSection.cors,
        AdminConsoleSection.accessControl,
      ],
    ),
    (
      'PLUGINS',
      Icons.extension_outlined,
      [AdminConsoleSection.pluginsManagement],
    ),
    (
      'ENTERPRISE',
      Icons.workspace_premium_outlined,
      [
        AdminConsoleSection.license,
        AdminConsoleSection.dataRetention,
        AdminConsoleSection.contentFlagging,
        AdminConsoleSection.sharedChannels,
      ],
    ),
  ];
}
